name: flutter_layout_test

description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2   #官方icon库
  english_words: ^3.1.0   #单词库
  flutter_spinkit: ^3.0.0   #官方动画库
  cached_network_image: ^0.7.0   #图片加载
  oktoast: ^2.1.6   #toast
  simple_permissions: ^0.1.9   #权限库
  image_picker: ^0.4.12+1   #系统相册
  flutter_picker: ^1.0.10  #picker
  image_cropper: ^1.0.0 #裁剪
  dio: ^2.1.0 #网络请求

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
        - images/flutter.jpg
        - images/flutter2.jpg
        - images/icon_image_default.png
        - images/icon_gridview_test1.png
        - images/icon_gridview_test2.png
        - images/icon_gridview_test3.png
        - images/icon_add.png
        - images/icon_close.png
        - images/icon_more.png





